const { ethers, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log(`\nDeploying to network: ${network.name}`);
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "ETH");

  if (balance === 0n) {
    console.error("❌ Deployer account has no ETH. Check your Ganache private key in hardhat.config.js");
    process.exit(1);
  }

  const VehicleHistory = await ethers.getContractFactory("VehicleHistory");
  const contract = await VehicleHistory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("\n✅ Contract deployed to:", address);

  // Write address to frontend config
  const jsDir = path.join(__dirname, "../public/js");
  if (!fs.existsSync(jsDir)) fs.mkdirSync(jsDir, { recursive: true });

  const configPath = path.join(jsDir, "contract-address.js");
  fs.writeFileSync(configPath, `// Auto-generated by deploy.js\nconst CONTRACT_ADDRESS = "${address}";\n`);
  console.log("📝 Written to public/js/contract-address.js");

  // Detect chain ID for MetaMask instructions
  const chainId = (await ethers.provider.getNetwork()).chainId;
  const rpcUrl = network.config.url || "http://127.0.0.1:8545";

  console.log("\n─── MetaMask network settings ──────────────────────────────────");
  console.log("RPC URL  :", rpcUrl);
  console.log("Chain ID :", chainId.toString());
  console.log("\n─── Next steps ──────────────────────────────────────────────────");
  console.log("1. node scripts/setup-db.js");
  console.log("2. Add private keys to hardhat.config.js → ganache.accounts");
  console.log("3. npm run seed");
  console.log("4. node server/server.js");
}

main().catch((e) => { console.error(e); process.exitCode = 1; });
